# Counties coordinates (lat, lon)
**Runs in about 30 s**

Two files are required to execute this code
- The top 500 cities in the US by population, based on 2010 census. Can be found at:
https://chronicdata.cdc.gov/500-Cities-Places/500-Cities-City-level-Data-GIS-Friendly-Format-201/pf7q-w24q

- All the US counties with the geolocation. Can be found at: https://www.weather.gov/gis/counties

In [25]:
# Import base packages
import pandas as pd
import numpy as np
import shapefile
import geopy.distance as gd
from fastkml import kml

In [26]:
# Specify absolute path (this is where you stored the downloaded files above)
coords_dir = "/Users/alessandropreviero/Desktop/vaccine-allocation/notebooks/counties_geo_clean.csv"
top_cities_dir = "/Users/alessandropreviero/Downloads/top500.csv"

### Read top cities

In [27]:
valid_cols = ['StateAbbr', 'PlaceName', 'Population2010', 'Geolocation']
cities_df = pd.read_csv(top_cities_dir, usecols=valid_cols).sort_values('Population2010', ascending=False, )

cities_df.rename(columns={
    'StateAbbr': 'state', 
    'PlaceName': 'city', 
    'Population2010': 'population', 
    'Geolocation': 'geolocation'
}, inplace=True)

# originally tuple of geolocation is a string, convert to numerical
cities_df['geolocation'] = [eval(v) for v in cities_df['geolocation']]

cities_df.reset_index(drop=True, inplace=True)
cities_df.head()

state          city  population                      geolocation
0    NY      New York     8175133   (40.694960689, -73.9313850409)
1    CA   Los Angeles     3792621  (34.1182277898, -118.408500088)
2    IL       Chicago     2695598  (41.8372950615, -87.6862308732)
3    TX       Houston     2099451  (29.7806691396, -95.3860033966)
4    PA  Philadelphia     1526006  (40.0093147808, -75.1333888571)

### Sub sample a portion of these cities using greedy approach

In [28]:
# For each state, find which ones have more than 5 cities
cities_per_state = cities_df.state.value_counts()
excess_states = cities_per_state[cities_per_state > 5].index.to_list()

In [29]:
# Put aside states with less than 5 cities
states_few_cities = cities_per_state[cities_per_state <= 5].index.to_list()
few_cities_df = cities_df[cities_df.state.isin(states_few_cities)]

In [30]:
# Greedy approach: pick most populus city in each state, compute its distance to other cities within state
# Then pick the furthest city from it, and randomly sample 40% of remaining cities.

# Keep track of the indices of cities in the ORIGINAL cities_df
all_indices = []

for st in excess_states:
    
    state_cities_df = cities_df[cities_df.state == st]
    top_city = state_cities_df.iloc[0]
    top_city_idx = state_cities_df.index[0]
    all_indices.append(top_city_idx)
    
    dists_from_top_city = []
    
    # Skip top city
    for idx in range(1, state_cities_df.shape[0]):
        other_city = state_cities_df.iloc[idx]
        dists_from_top_city.append(gd.distance(top_city['geolocation'], other_city['geolocation']).km)
    
    # Pick furthest city
    furthest_city = state_cities_df.iloc[np.argmax(dists_from_top_city) + 1]
    furthest_city_idx = state_cities_df.index[np.argmax(dists_from_top_city) + 1]
    all_indices.append(furthest_city_idx)
    
    # Now sample at random 50% from the remaining cities
    remaining_cities_ids = state_cities_df.index.to_list()
    [remaining_cities_ids.remove(x) for x in [top_city_idx, furthest_city_idx]]
    
    sampled_cities = np.random.choice(remaining_cities_ids, int(len(remaining_cities_ids) * 0.4), replace=False)
    [all_indices.append(x) for x in sampled_cities]

resampled_cities = cities_df.iloc[all_indices]

In [31]:
# Sanity check that we didn't take duplicate indices
print(len(all_indices))
print(len(np.unique(all_indices)))

201
201


In [32]:
# Last sanity check - control that indices in resampled_cities and indices in few_cities_df dont overlap
resampled_set = set(all_indices)
few_cities_set = set(few_cities_df.index.to_list())

print(len(set.intersection(resampled_set, few_cities_set)))

0


In [33]:
# Finally concatenate the two dataframes
final_cities_df = few_cities_df.append(resampled_cities, ignore_index=True)
final_cities_df

state        city  population                      geolocation
0      HI    Honolulu      953207  (21.4588039305, -157.973296737)
1      MD   Baltimore      620961  (39.3084523991, -76.6160492311)
2      DC  Washington      601723  (38.9099241426, -77.0147205666)
3      KY  Louisville      597337  (38.1777689918, -85.6664099974)
4      NV   Las Vegas      583756  (36.2274148438, -115.262670095)
..    ...         ...         ...                              ...
244    LA  Shreveport      199311  (32.4671618864, -93.7962236108)
245    LA      Kenner       66702  (30.0106937201, -90.2550320135)
246    IA  Des Moines      203433  (41.5741349525, -93.6165066086)
247    IA  Sioux City       82684  (42.4963149039, -96.3913834837)
248    IA   Iowa City       67862  (41.6558950332, -91.5308854927)

[249 rows x 4 columns]

In [34]:
# Sanity check that we have 51 states

print(len(final_cities_df.state.unique()) == 51)

True


### Read all counties

In [35]:
counties_df = pd.read_csv(coords_dir)
counties_df.head()
counties_df['geolocation'] = [eval(x) for x in counties_df['geolocation']]

In [36]:
# Sanity check there is at least one county for each of the above states

counties_df.head()

state          county  fips fips_state           geolocation
0    AK  aleutians east  2013   AK 02013   (55.4039, -161.863)
1    AK  aleutians west  2016   AK 02016  (52.8883, -111.1392)
2    AK       anchorage  2020   AK 02020  (61.1501, -149.1067)
3    AK          bethel  2050   AK 02050  (60.9126, -159.7207)
4    AK     bristol bay  2060   AK 02060  (58.7423, -156.7013)

In [37]:
def find_top_county_per_city(final_cities_df, counties_df):
    
    num_cities = final_cities_df.shape[0]
    num_counties = counties_df.shape[0]
    
    # Populate dictionary mapping cities to best county 
    # Cities can have same name across states, so need to be more specific in the dictionary key
    city_to_county = {f"{final_cities_df.iloc[i]['state']}, {final_cities_df.iloc[i]['city']}":''
                      for i in range(num_cities)}
    
    # For each city compute distance from it to each county (lat, lon order)
    for i, city in enumerate(final_cities_df.city):

        dists = []
        city_coord = final_cities_df.iloc[i]['geolocation']
        
        # Only counties within the city's state can be used
        counties_state_df = counties_df[counties_df.state == final_cities_df.iloc[i]['state']]

        for j, county in enumerate(counties_state_df.county):
            county_coord = counties_state_df.iloc[j]['geolocation']
            dists.append(gd.distance(city_coord, county_coord).km)
        
        # There are many counties with the same name, need to track State as well
        best_idx = np.argmin(dists)
        city_to_county[f"{final_cities_df.iloc[i]['state']}, {final_cities_df.iloc[i]['city']}"] = \
        counties_state_df.iloc[best_idx][['fips_state', 'state']].to_numpy()
    
    return city_to_county

In [38]:
dc = find_top_county_per_city(final_cities_df, counties_df)

In [39]:
# Sanity: check we have one center per city
print(len(dc))

249


In [40]:
# Show an example

for k, v in dc.items():
    print(f"State: {v[1]}\nCity: {k}\nCounty: {v[0]}")
    break

State: HI
City: HI, Honolulu
County: HI 15003


### Build final dataframe

In [41]:
colnames = ['state', 'city', 'fips', 'city_geolocation', 'county_geolocation', 'city_pop']
final = []
for city, county in dc.items():
    
    bare_city = city.split(',')[1].strip()

    county_arr = counties_df[(counties_df.fips_state==county[0]) &
                             (counties_df.state==county[1])
                            ][['state', 'geolocation']].to_numpy()[0]
    
    city_arr = final_cities_df[(final_cities_df.city == bare_city) &
                         (final_cities_df.state == county[1])
                        ][['geolocation', 'population']].to_numpy()[0]
    
    final.append([county_arr[0], bare_city, county[0], city_arr[0], county_arr[1], city_arr[1]])

complete_df = pd.DataFrame(final, columns=colnames).sort_values('city_pop', ascending=False)
complete_df.reset_index(drop=True, inplace=True)


In [76]:
complete_df

state          city      fips                 city_geolocation  \
0      NY      New York  NY 36047   (40.694960689, -73.9313850409)   
1      CA   Los Angeles  CA 06037  (34.1182277898, -118.408500088)   
2      IL       Chicago  IL 17031  (41.8372950615, -87.6862308732)   
3      TX       Houston  TX 48201  (29.7806691396, -95.3860033966)   
4      PA  Philadelphia  PA 42101  (40.0093147808, -75.1333888571)   
..    ...           ...       ...                              ...   
244    SC     Rock Hill  SC 45091  (34.9403611496, -81.0249178286)   
245    NY   Schenectady  NY 36093  (42.8025204414, -73.9275333869)   
246    WY      Cheyenne  WY 56021  (41.1460804265, -104.789064332)   
247    WV    Charleston  WV 54039   (38.3484079736, -81.632165003)   
248    VT    Burlington  VT 50007  (44.4876245694, -73.2314828365)   

       county_geolocation  city_pop  
0     (40.6447, -73.9472)   8175133  
1    (34.3203, -118.2252)   3792621  
2     (41.8399, -87.8167)   2695598  
3     (29.8588, -95.3963)   2099451  
4     (40.0076, -75.1338)   1526006  
..                    ...       ...  
244   (34.9747, -81.1845)     66154  
245   (42.8182, -74.0585)     66135  
246  (41.3071, -104.6896)     59466  
247   (38.3365, -81.5281)     51400  
248   (44.4609, -73.0809)     42417  

[249 rows x 6 columns]

### Build matrix of distances between counties

In [43]:
# Pre-populate array (rows are the assigned centers, columns are each existing county)
counties_dists = np.ones(shape=(complete_df.shape[0], counties_df.shape[0])) * -1.0

for i in range(complete_df.shape[0]):
    
    # Compute distance from selected county to all other counties within the same state
    dists = []
    center_coord = complete_df.iloc[i]['county_geolocation']

    counties_state_df = counties_df[counties_df.state == complete_df.iloc[i]['state']]
    nonzero_indices = counties_state_df.index
    
    for j, county in enumerate(counties_state_df.county):
        county_coord = counties_state_df.iloc[j]['geolocation']
        dists.append(gd.distance(center_coord, county_coord).km)
    
    counties_dists[i, nonzero_indices] = dists

In [44]:
columns = counties_df.fips_state.to_numpy()
index = complete_df['state'] + ', ' + complete_df['city']

counties_dists_df = pd.DataFrame(counties_dists, 
                                 columns=columns, 
                                 index=index)

In [45]:
counties_dists_df.head()

AK 02013  AK 02016  AK 02020  AK 02050  AK 02060  AK 02068  \
NY, New York          -1.0      -1.0      -1.0      -1.0      -1.0      -1.0   
CA, Los Angeles       -1.0      -1.0      -1.0      -1.0      -1.0      -1.0   
IL, Chicago           -1.0      -1.0      -1.0      -1.0      -1.0      -1.0   
TX, Houston           -1.0      -1.0      -1.0      -1.0      -1.0      -1.0   
PA, Philadelphia      -1.0      -1.0      -1.0      -1.0      -1.0      -1.0   

                  AK 02070  AK 02090  AK 02100  AK 02105  ...  WY 56027  \
NY, New York          -1.0      -1.0      -1.0      -1.0  ...      -1.0   
CA, Los Angeles       -1.0      -1.0      -1.0      -1.0  ...      -1.0   
IL, Chicago           -1.0      -1.0      -1.0      -1.0  ...      -1.0   
TX, Houston           -1.0      -1.0      -1.0      -1.0  ...      -1.0   
PA, Philadelphia      -1.0      -1.0      -1.0      -1.0  ...      -1.0   

                  WY 56029  WY 56031  WY 56033  WY 56035  WY 56037  WY 56039  \
NY, New York          -1.0      -1.0      -1.0      -1.0      -1.0      -1.0   
CA, Los Angeles       -1.0      -1.0      -1.0      -1.0      -1.0      -1.0   
IL, Chicago           -1.0      -1.0      -1.0      -1.0      -1.0      -1.0   
TX, Houston           -1.0      -1.0      -1.0      -1.0      -1.0      -1.0   
PA, Philadelphia      -1.0      -1.0      -1.0      -1.0      -1.0      -1.0   

                  WY 56041  WY 56043  WY 56045  
NY, New York          -1.0      -1.0      -1.0  
CA, Los Angeles       -1.0      -1.0      -1.0  
IL, Chicago           -1.0      -1.0      -1.0  
TX, Houston           -1.0      -1.0      -1.0  
PA, Philadelphia      -1.0      -1.0      -1.0  

[5 rows x 3141 columns]

In [46]:
# One more sanity check (check distance of center with itself is 0)
example = counties_dists_df.loc["NY, New York"]

In [23]:
sum(sum(counties_dists>-1))

19480

In [63]:
m = np.argwhere(counties_dists > -1)
np.where(counties_dists>1)

(array([  0,   0,   0, ..., 248, 248, 248]),
 array([1980, 1981, 1982, ..., 2949, 2950, 2951]))

In [75]:
np.where(counties_dists[:, 102] > -1)[0]

array([ 73, 166, 216, 227, 238])

### Save all these big boys

In [24]:
complete_df.to_csv('selected_centers.csv')
counties_dists_df.to_csv('counties_distances.csv')